log:
  filename: log
  level: info
  stdout: true

redis:
  host: 0.0.0.0
  port: "6379"
  # password: foobared
  publishChannel: 'from-akka-apps-redis-channel'

# in mhz
sampleRate: '16'

vosk:
  startMessage: '{"config": { "sample_rate": ""} }'
  endMessage: '{"eof" : 1 }'
  servers:
    en-US: wss://lucas.elos.dev/voskEN
    es-ES: wss://lucas.elos.dev/voskES
    pt-BR: wss://lucas.elos.dev/voskPT
    fr-FR: wss://lucas.elos.dev/voskFR

whispering:
  startMessage: '{"config": { "sample_rate": ""} }'
  endMessage: '{"eof" : 1 }'
  servers:
    en-US: wss://lucas.elos.dev/whispering

freeswitch:
  ip: 0.0.0.0
  port: 8021
  password:
